services:
  api:
    build: ./api
    ports:
      - "3333:3333"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL = "http://localhost:3333"
    depends_on:
      - api
